In [1]:
import pandas as pd
df = pd.read_csv('Sample_File.csv')
df.head()

           Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [2]:
df.to_json('Sample_File_json.json')
df = pd.read_json('Sample_File_json.json')
df

           Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male

In [3]:
df.to_excel('Sample_File_Excel.xlsx',index = False)
df = pd.read_excel('Sample_File_excel.xlsx')
df

           Name  Age  Gender
0        Nithin   24    Male
1         Manoj   30    Male
2  Shivashankar   44    Male
3        Swathi   18  Female
4   Pareekshith   28    Male